services:
  - type: web
    name: travectio-api
    runtime: node
    region: ohio
    plan: starter
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: travectio-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    domains:
      - travectio-api.onrender.com

databases:
  - name: travectio-db
    databaseName: travectio
    user: travectio_user
    region: ohio
    plan: free
    ipAllowList: []